---
platforms:
  - name: ubuntu-14.04
    driver:
        gui: false
        box: pingworks_ubuntu-14.04_chef-12.4.1-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-14.04_chef-12.4.1-1.box
        #network:
        #  - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[workshopbox_doc::default]
      - recipe[pw_testhelper::default]
    attributes:
      workshopbox_doc:
        workshop_name: __WORKSHOP_NAME__
        build_number: __BUILD_NUMBER__
