---
platforms:
  - name: ubuntu-16.04
    driver:
        gui: false
        box: pingworks_ubuntu-16.04_chef-12.7.2-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-16.04_chef-12.7.2-1.box
        #network:
        #  - ["forwarded_port", {guest: 80, host: 8080}]
suites:
  - name: default
    run_list:
      - recipe[secret_service::default]
    attributes:
      secret_service:
        domain: __WORKSHOP_NAME__
