---
platforms:
  - name: ubuntu-14.04
    driver:
        gui: false
        box: pingworks_ubuntu-14.04_chef-12.4.1-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-14.04_chef-12.4.1-1.box

suites:
  - name: default
    run_list:
      - recipe[secret_service::default]
    attributes:
      secret_service:
        domain: __WORKSHOP_NAME__
        accessuser: __WORKSHOP_ACCESSUSER__
        
