---
platforms:
  - name: ubuntu-16.04
    driver:
        gui: false
        box: pingworks_ubuntu-16.04_chef-12.7.2-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-16.04_chef-12.7.2-1.box
        #network:
        #  - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[workshopbox_doc::default]
      - recipe[pw_testhelper::default]
    attributes:
      workshopbox_doc:
        build_number: __BUILD_NUMBER__
