---
platforms:
  - name: ubuntu-16.04
    driver:
        gui: false
        box: pingworks_ubuntu-16.04_chef-12.7.2-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-16.04_chef-12.7.2-1.box

suites:
  - name: userinject
    run_list:
      - recipe[workshopbox_doc::noop]
