---
driver:
  name: vagrant
  customize:
    memory: 4096
    vram: 64
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo
  require_chef_omnibus: false

platforms:
  - name: ubuntu-14.04
    driver:
        gui: true
        box: pingworks_ubuntu-14.04_chef-12.4.1-1
        box_url: http://vagrant.pingworks.net/pingworks_ubuntu-14.04_chef-12.4.1-1.box

suites:
  - name: default
    run_list:
      - recipe[workshopbox_doc::default]
      #- recipe[secret_service::default]
    attributes:
