name 'workshopbox_doc'
maintainer 'Alexander Birk'
maintainer_email 'birk@pingworks.de'
license 'Apache 2.0'
description 'Installs/Configures workshopbox Appliance Documentation'
long_description 'Installs/Configures workshopbox Appliance Documentation'
version '0.4.2'

depends 'apt', '~> 5.1.0'
depends 'ohai'
depends 'secret_service'
depends 'pw_testhelper'
