name 'workshopbox_doc'
maintainer 'Alexander Birk'
maintainer_email 'birk@pingworks.de'
license 'Apache 2.0'
description 'Installs/Configures workshopbox Appliance Documentation'
long_description 'Installs/Configures workshopbox Appliance Documentation'
version '0.3.1'

depends 'apt'
depends 'ohai'
depends 'secret_service', '>=0.2.10'
depends 'pw_testhelper'
